### ISSUE TITLE
Runnable example in a script file

### ISSUE THREAD

**Issue by fpriyatna** [SDM-TIB/Ontario#1]
Hi there, this tool looks interesting. Unfortunately, the instructions provided in the wiki are not clear and easy to follow and in some steps, they give some errors.

Would it be possible for you to provide all the resources (mappings, dataset, queries) of an example and a script so that I can execute without the need for any modifications?

Thanks

**Comment by prohde** [comment]
Hi,

we will take care of your issue soon.

**Comment by keme686** [comment]
Check out the instruction inside `demo` folder.
