### ISSUE TITLE
Error during Docker Installation

### ISSUE THREAD

**Issue by kapsali29** [SDM-TIB/Ontario#3]
Hi there,

I am trying to install Ontario using Docker but i get the following error:

**/usr/bin/env: 'bash\r': No such file or directory**

The commands I am using are the following and with the corresponding order:
+ `docker build -t ontario:0.3 .`
+ `docker run -p 5000:5000 ontario:0.3`

Thanks in advance

**Comment by prohde** [comment]
Hi,

I can not reproduce this error, however, I had the same issue as you mentioned in #4 which should be fixed by now. Could you please provide us more information, like your OS? I am not sure but maybe this is related to the same problem as reported in #4. Does the fix for that also eliminate the problem reported here?

**Comment by kapsali29** [comment]
Hi,

First of all I would like to thank you for your immediate response, my OS is Win10 and I have installed Docker engine for Win. This error I think is not related with the one reported in issue #4 as during docker run command  this error is appeared **/usr/bin/env: 'bash\r': No such file or directory**. Probably this directory is a part of Ontario Dockerfile or something like that, I mean that is not OS specific error, but probably something occured with Dockerfile commands.

Thanks in advance

**Comment by prohde** [comment]
After fixing #4, I don't have any problems running the above commands on Ubuntu 18.04. But I can test it on Windows 10 tomorrow.

**Comment by kapsali29** [comment]
Yes that error occured on Win10

**Comment by prohde** [comment]
I wasn't able to reproduce this error on Windows 10 with Docker Desktop 2.2.0.5 (and Linux containers of course) and the latest commit. Does this error still occur for you?

The best way to play around with Ontario is to follow the read me in https://github.com/SDM-TIB/Ontario/tree/master/demo
