### ISSUE TITLE
 starting container process caused "exec: \"/Ontario/start_sparql_service.sh\": permission denied": unknown.

### ISSUE THREAD

**Issue by kapsali29** [SDM-TIB/Ontario#4]
Hi there,

During Ontario docker installation, now I am trying on a Ubuntu instance, I get the following error after docker run command:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/Ontario/start_sparql_service.sh\": permission denied": unknown.
ERRO[0001] error waiting for container: context canceled
```

Probably the error above caused because the script **start_sparql_service.sh** is not executable and I believe that  you should include in your Dockerfile  a bash command that makes the script executable.

Thanks in advance

**Comment by prohde** [comment]
Hi,

indeed the file was not executable. This should be fixed in 62adca6.
