### ISSUE TITLE
Issue in Apache Drill mediator "sparql2drill.py" 

### ISSUE THREAD

**Issue by code8git** [SDM-TIB/Ontario#6]
Hi,

There is some exceptions coming when I try to use Apache Drill for the "ChEBI-TSV" dataset in the demo. The exceptions is thrown by the Apache Drill mediator "sparql2drill.py". 

Below are Apache Drill configurations in the "datasources.json" file.

{
     "name": "ChEBI-TSV",
     "ID": "http://tib.eu/chebi-tsv",
     "url": "http://localhost:8047",
     "params": {},
    "type": "LOCAL_TSV",
    "mappings": [
        "D:\\code\\python\\ontario\\mappings\\tsv\\chebi\\Compound.ttl"
        ]
}

Your support will be appreciated in this regard.

Thank you.

**Comment by prohde** [comment]
Is this the error you are getting?

> File "/home/\*\*\*/\*\*\*/Ontario/ontario/wrappers/drill/sparql2drill.py", line 37, in \_\_init__
> &nbsp;&nbsp;self.host, self.port = self.url.split(':')
ValueError: too many values to unpack (expected 2)

**Comment by code8git** [comment]
Yes I am getting this exception.
